import asyncio
import json
import math
from pathlib import Path

import httpx
import pytest

from app.baidu.client import BaiduClient
from app.baidu.errors import BaiduAuthError, BaiduApiError
from app.map_assets import alignment_grid, display_corners_wgs84, export_map_asset, map_asset_input, valid_map_asset


SOURCE = Path(__file__).resolve().parents[2] / "frontend/src/data/demoBoundary.wgs84.json"
GRID, GRID_POINTS = alignment_grid(map_asset_input(json.loads(SOURCE.read_text(encoding="utf-8"))))
EXPECTED_BATCHES = 2 + math.ceil(len(GRID_POINTS) / 100)


def mock_client(handler):
    return BaiduClient(ak="test-map-key", transport=httpx.MockTransport(handler))


def converted_response(request):
    points = [tuple(map(float, point.split(","))) for point in request.url.params["coords"].split(";")]
    # Test data only. The production asset is generated by Baidu, not this stub.
    return httpx.Response(200, json={"status": 0, "result": [
        {"x": lng + .01, "y": lat + .01} for lng, lat in points]})


def test_fixed_asset_batches_deduplicates_and_skips_repeat_requests(tmp_path):
    batches = []

    def handler(request):
        assert request.url.path == "/geoconv/v2/"
        assert request.url.params["model"] == "2"
        batch = request.url.params["coords"].split(";")
        assert len(batch) <= 100
        batches.append(batch)
        return converted_response(request)

    async def run():
        client = mock_client(handler)
        output = tmp_path / "map.bd09.json"
        try:
            asset, updated = await export_map_asset(SOURCE, output, client)
            assert updated
            assert len(batches) == EXPECTED_BATCHES
            flattened = [point for batch in batches[:2] for point in batch]
            assert len(flattened) == len(set(flattened))
            assert valid_map_asset(asset, map_asset_input(json.loads(SOURCE.read_text(encoding="utf-8"))))
            assert asset["boundary"]["geometry"]["coordinates"][0][0] == asset["boundary"]["geometry"]["coordinates"][0][-1]
            assert "test-map-key" not in output.read_text(encoding="utf-8")
            before = output.stat().st_mtime_ns
            same, updated = await export_map_asset(SOURCE, output, client)
            assert same == asset and not updated
            assert len(batches) == EXPECTED_BATCHES
            assert output.stat().st_mtime_ns == before
        finally:
            await client.aclose()
    asyncio.run(run())


def test_existing_asset_can_be_used_without_an_ak(tmp_path):
    async def run():
        output = tmp_path / "map.bd09.json"
        client = mock_client(converted_response)
        try:
            await export_map_asset(SOURCE, output, client)
        finally:
            await client.aclose()
        client = BaiduClient(ak="", transport=httpx.MockTransport(
            lambda request: pytest.fail("Existing geometry must not make any request")))
        try:
            _, updated = await export_map_asset(SOURCE, output, client)
            assert not updated
        finally:
            await client.aclose()
    asyncio.run(run())


def test_refresh_failure_keeps_last_good_asset(tmp_path):
    async def run():
        output = tmp_path / "map.bd09.json"
        client = mock_client(converted_response)
        try:
            await export_map_asset(SOURCE, output, client)
        finally:
            await client.aclose()
        before = output.read_bytes()
        requests = 0

        def handler(request):
            nonlocal requests
            requests += 1
            return converted_response(request) if requests == 1 else httpx.Response(200, json={"status": 240})

        client = mock_client(handler)
        try:
            with pytest.raises(BaiduAuthError, match="240"):
                await export_map_asset(SOURCE, output, client, refresh=True)
            assert output.read_bytes() == before
            assert requests == 2
        finally:
            await client.aclose()
    asyncio.run(run())


def test_changed_boundary_regenerates_only_on_explicit_script_run(tmp_path):
    async def run():
        output = tmp_path / "map.bd09.json"
        source = tmp_path / "boundary.json"
        boundary = json.loads(SOURCE.read_text(encoding="utf-8"))
        source.write_text(json.dumps(boundary), encoding="utf-8")
        client = mock_client(converted_response)
        try:
            first, _ = await export_map_asset(source, output, client)
            boundary["geometry"]["coordinates"][0][1][0] += .0001
            source.write_text(json.dumps(boundary), encoding="utf-8")
            second, updated = await export_map_asset(source, output, client)
            assert updated and second["input"] != first["input"]
            assert client.cache_stats["apiRequests"] == EXPECTED_BATCHES * 2
        finally:
            await client.aclose()
    asyncio.run(run())


def test_nonfinite_conversion_is_not_published(tmp_path):
    async def run():
        client = mock_client(converted_response)
        async def invalid_conversion(points, source_coord_type, **kwargs):
            return [(float("nan"), point[1]) for point in points]
        client.convert_coordinates = invalid_conversion
        try:
            output = tmp_path / "map.bd09.json"
            with pytest.raises(BaiduApiError, match="有效"):
                await export_map_asset(SOURCE, output, client)
            assert not output.exists()
        finally:
            await client.aclose()
    asyncio.run(run())


def test_display_extent_still_covers_the_1300m_padding():
    inputs = map_asset_input(json.loads(SOURCE.read_text(encoding="utf-8")))
    ring = inputs["boundaryCoordinatesWgs84"]
    corners = display_corners_wgs84(inputs)
    assert corners[0][0] < min(point[0] for point in ring)
    assert corners[0][1] > max(point[1] for point in ring)
    assert corners[2][0] > max(point[0] for point in ring)
    assert corners[2][1] < min(point[1] for point in ring)


def test_alignment_grid_covers_display_extent_and_contains_exact_origin():
    inputs = map_asset_input(json.loads(SOURCE.read_text(encoding="utf-8")))
    grid, points = alignment_grid(inputs)
    assert grid["stepMeters"] == 250 and grid["localAxis"] == "east-south"
    assert inputs["originWgs84"] in points
    corners = display_corners_wgs84(inputs)
    assert points[0][0] <= corners[0][0] and points[0][1] >= corners[0][1]
    assert points[-1][0] >= corners[2][0] and points[-1][1] <= corners[2][1]


def test_grid_conversion_failure_keeps_last_good_asset(tmp_path):
    async def run():
        output = tmp_path / "map.bd09.json"
        writer = mock_client(converted_response)
        try:
            await export_map_asset(SOURCE, output, writer)
        finally:
            await writer.aclose()
        before = output.read_bytes()
        calls = 0
        def handler(request):
            nonlocal calls
            calls += 1
            return converted_response(request) if calls <= 2 else httpx.Response(200, json={"status": 1})
        reader = mock_client(handler)
        try:
            with pytest.raises(BaiduApiError):
                await export_map_asset(SOURCE, output, reader, refresh=True)
            assert calls == 3 and output.read_bytes() == before
        finally:
            await reader.aclose()
    asyncio.run(run())


def test_degenerate_but_finite_grid_is_not_published(tmp_path):
    calls = 0
    async def run():
        nonlocal calls
        def handler(request):
            nonlocal calls
            calls += 1
            if calls <= 2:
                return converted_response(request)
            count = len(request.url.params["coords"].split(";"))
            return httpx.Response(200, json={"status": 0, "result": [{"x": 121.5, "y": 31.3}] * count})
        writer = mock_client(handler)
        output = tmp_path / "map.bd09.json"
        try:
            with pytest.raises(BaiduApiError, match="退化"):
                await export_map_asset(SOURCE, output, writer)
            assert not output.exists()
        finally:
            await writer.aclose()
    asyncio.run(run())
